resources:
  - 00_nrf-sa.yaml
  - 01_nrf-rbac.yaml
  - 02_nrf-configmap.yaml
  - 03_nrf-service.yaml
  - 04_nrf-deployment.yaml

namespace: f5gc
images:
- name: ghcr.io/sumichaaan/free5gc-k8s/f5gc-nrf:v3.0.4
  newName: reg.f5.local/free5gc-k8s/f5gc-nrf
  newTag: v3.0.5

secretGenerator:
- name: f5gc-nrf-tls-secret
  namespace: f5gc
  files:
  - cert/nrf.pem
  - cert/nrf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
