resources:
  - 00_udr-sa.yaml
  - 01_udr-rbac.yaml
  - 02_udr-configmap.yaml
  - 03_udr-service.yaml
  - 04_udr-deployment.yaml

namespace: f5gc
images:
- name: ghcr.io/sumichaaan/free5gc-k8s/f5gc-udr:v3.0.4
  newName: reg.f5.local/free5gc-k8s/f5gc-udr
  newTag: v3.0.5

secretGenerator:
- name: f5gc-udr-tls-secret
  namespace: f5gc
  files:
  - cert/udr.pem
  - cert/udr.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
