resources:
  - 00_smf-sa.yaml
  - 01_smf-rbac.yaml
  - 02_smf-configmap.yaml
  - 03_smf-service.yaml
  - 04_smf-multus.yaml
  - 05_smf-deployment.yaml

namespace: f5gc

images:
- name: ghcr.io/sumichaaan/free5gc-k8s/f5gc-smf:v3.0.4
  newName: reg.f5.local/free5gc-k8s/f5gc-smf
  newTag: v3.0.5

secretGenerator:
- name: f5gc-smf-tls-secret
  namespace: free5gc
  files:
  - cert/smf.pem
  - cert/smf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
