apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-webui
  name: f5gc-webui
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.39
  ports:
  - name: http-f5gc-webui
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: f5gc-webui
