resources:
  - 00_webui-sa.yaml
  - 01_webui-rbac.yaml
  - 02_webui-configmap.yaml
  - 03_webui-service.yaml
  - 04_webui-deployment.yaml

namespace: f5gc

images:
- name: ghcr.io/sumichaaan/free5gc-k8s/f5gc-webui:v3.0.4
  newName: reg.f5.local/free5gc-k8s/f5gc-webui
  newTag: v3.0.5
