resources:
  - 00_upf-sa.yaml
  - 01_upf-rbac.yaml
  - 02_upf-configmap.yaml
  - 03_upf-service.yaml
  - 04_upf-multus.yaml
  - 05_upf-deployment.yaml

namespace: f5gc
images:
- name: ghcr.io/sumichaaan/free5gc-k8s/f5gc-upf:v3.0.4
  newName: reg.f5.local/free5gc-k8s/f5gc-upf
  newTag: v3.0.5
