resources:
  - 00_amf-sa.yaml
  - 01_amf-rbac.yaml
  - 02_amf-configmap.yaml
  - 03_amf-service.yaml
  - 04_amf-multus.yaml
  - 05_amf-deployment.yaml

namespace: f5gc
images:
- name: ghcr.io/sumichaaan/free5gc-k8s/f5gc-amf:v3.0.4
  newName: reg.f5.local/free5gc-k8s/f5gc-amf
  newTag: v3.0.5

secretGenerator:
- name: f5gc-amf-tls-secret
  namespace: f5gc
  files:
  - cert/amf.pem
  - cert/amf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
