resources:
  - 00_ausf-sa.yaml
  - 01_ausf-rbac.yaml
  - 02_ausf-configmap.yaml
  - 03_ausf-service.yaml
  - 04_ausf-deployment.yaml

namespace: f5gc
images:
- name: ghcr.io/sumichaaan/free5gc-k8s/f5gc-ausf:v3.0.4
  newName: reg.f5.local/free5gc-k8s/f5gc-ausf
  newTag: v3.0.5

secretGenerator:
- name: f5gc-ausf-tls-secret
  namespace: f5gc
  files:
  - cert/ausf.pem
  - cert/ausf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true
